### ISSUE TITLE
Proposal: bpftrace CI

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#150]
If you are just making a comment, ignore/delete those fields and file your issue.

### Name, email, company, job title

Ed Vielmetti, Packet @vielmetti 
Zi Shen Lim, Marvell @zlim

### Project Title and description

We propose to set up CI for bpftrace, targeting x86 and arm64 systems.

bpftrace is a high-level tracing language for Linux eBPF. Brendan Gregg has a blog post, [bpftrace (DTrace 2.0) for Linux 2018](http://www.brendangregg.com/blog/2018-10-08/dtrace-for-linux-2018.html), which has a good overview. 

> The private bpftrace repository has just been made public, which is big news for DTrace fans. Created by Alastair Robertson, bpftrace is an open source high-level tracing front-end that lets you analyze systems in custom ways. It's shaping up to be a DTrace version 2.0: more capable, and built from the ground up for the modern era of the eBPF virtual machine. eBPF (extended Berkeley Packet Filter) is in the Linux kernel and is the new hotness in systems engineering. It is being developed for BSD, too, where BPF originated.

A relevant issue is https://github.com/iovisor/bpftrace/issues/130 (Set up CI and Code Coverage), from @ajor , currently marked as "help wanted".

### Which members of the community would benefit from your work?

Anyone doing kernel development work. This is especially of interest to arm64 kernel developers, who have been working without this tool so far.

### Is the code that you’re going to run 100% open source? 

Licensed under Apache 2.0, see https://github.com/iovisor/bpftrace/blob/master/LICENSE

https://github.com/iovisor/bpftrace

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

Let us know if you need short-term (one time) support, or if this is a request for
continuous ongoing support. If possible, please identify foundations or other
support organizations that can help with long-running projects.

In the short term, at least one x86 and one arm64 system to install a CI system on. In the long term, this should have foundational support.

### Describe the continuous integration (CI) system in use or desired for this project.

Are you testing every check-in on arm64? (Would you like to?) If so, share a public URL of a CI dashboard.

The goal is to do CI. The relevant issue https://github.com/iovisor/bpftrace/issues/130 notes that CI is working for x86 using Travis CI, but the Travis kernel is too old to run tests of `bpftrace`. Also under consideration are Drone Cloud and Gitlab. There is no plan to remove Travis CI, just to augment it.

### Describe the monitoring system in use or desired for this project.

Are you running an agent on any long-running servers to track system status? Are you willing to share that data with the project? Examples might include a Prometheus metric endpoint or a Grafana dashboard.

Various CI systems export various dashboards, we'll use those.

### Please state your contributions to the open source community and any other relevant initiatives

[TBD]

**Comment by zlim** [comment]
POC Matrix
- OS: Alpine, Ubuntu 18.04
- Arch: arm64, x64
- build, runtime tests

Need
- [ ] x64 instance
- [ ] arm64 instance
- [ ] gitlab-runner [arm64](https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/725) [x64](https://docs.gitlab.com/runner/install/linux-manually.html)

---
Aside
- [ ] bcc distro packaging (on arm64)

Bonus
- OS: Fedora 28, Fedora 29
- Kernel: 5.0

**Comment by vielmetti** [comment]
A ThunderX2 system in EWR has been reserved to this project, and @zlim has been invited.

Let me know if any other collaborators should be added in.

The account has sufficient permissions to add an x86 system, but nothing has been added yet, pending sizing of the request. There is sufficient inventory in EWR to make it happen there.

If it's possible that this would also be tested in virtual machines, I'm currently recommending `libvirt` as a good mechanism for setting that up, in preference to some other options that are more heavyweight.

We'll need to address the `gitlab-runner` question by referring to https://gitlab.com/gitlab-org/gitlab-runner/merge_requests/725 - a comment in that issue by you @zlim would be welcomed, as I have spoken my bit several times already.

**Comment by vielmetti** [comment]
Noted also that the ThunderX2 systems only have Ubuntu 16.04 LTS currently available, and that for this project we'd want for sure to have Ubuntu 18.04 LTS due to its improved `libvirt`.

**Comment by vielmetti** [comment]
This is well underway, machine is assigned, closing.

**Comment by zlim** [comment]
A public GitLab project is setup at https://gitlab.com/zlim1/bpftrace-ci.
The CI/CI>Pipelines dashboard is available at https://gitlab.com/zlim1/bpftrace-ci/pipelines.

A custom build of aarch64 gitlab-runner runs on `Type 2A4` (ThunderX2), for aarch64 CI coverage (currently missing in upstream).
An upstream build of x86_64 gitlab-runner runs on `t1.small.x86`, as baseline for comparison against upstream x86_64 CI (Travis).

Container images for the build dependencies are tagged and available at https://gitlab.com/zlim1/bpftrace-ci/container_registry, for both aarch64 and x86_64.

**TODO**
- [ ] bpftrace: triage test failures on aarch64 and fix bugs!
- [ ] distro: bcc package for aarch64 (dependency for bpftrace)
- [ ] container registry: multi-arch images

**Comment by zlim** [comment]
Note: fedora29 is missing bcc-devel for aarch64.
This patch appears to address the packaging issue for aarch64: https://src.fedoraproject.org/rpms/bcc/c/2f05fca191b9c9a216bd0380e9eb3e07a5f97ab2?branch=master
